# Generated by Django 3.0.8 on 2020-08-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, verbose_name='le code du fournisseur')),
                ('nom_fournisseur', models.CharField(max_length=100, verbose_name="le nom de l'organisme fournisseur")),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=30, verbose_name='nom du Médicament')),
                ('alerte', models.CharField(max_length=70, verbose_name='seuil à ne pas franchir')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, verbose_name='code personne')),
                ('nom', models.CharField(max_length=40, verbose_name='nom de la personne')),
                ('prenom', models.CharField(max_length=50, verbose_name='prenom de la personne')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
            },
        ),
        migrations.CreateModel(
            name='Type_personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=70, verbose_name='la personne qui récupère les médicaments')),
                ('description', models.TextField(verbose_name='description du type de personne')),
            ],
            options={
                'verbose_name': 'Type de personne',
                'verbose_name_plural': 'Type de personnes',
            },
        ),
        migrations.CreateModel(
            name='Recuperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantite', models.FloatField(max_length=10, verbose_name='Quantité recuperée')),
                ('medicaments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Medicament')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Personne')),
            ],
            options={
                'verbose_name': 'Recuperation',
                'verbose_name_plural': 'Recuperations',
            },
        ),
        migrations.AddField(
            model_name='personne',
            name='Type_personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Type_personne', verbose_name='la personne qui récupère les médicaments'),
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date de livraison')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Fournisseur', verbose_name='le fournisseur de la livraison')),
            ],
            options={
                'verbose_name': 'Livraision',
                'verbose_name_plural': 'Livraisons',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacth_id', models.CharField(blank=True, max_length=25)),
                ('quantite_batch', models.FloatField(max_length=10)),
                ('Livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Livraison')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Medicament')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batch',
            },
        ),
    ]
