# Generated by Django 3.0.8 on 2020-07-29 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('nom_fournisseur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personnes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type_personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=70)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recuperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantite', models.FloatField(max_length=10)),
                ('Medicaments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Medicaments')),
                ('Personnes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Personnes')),
            ],
        ),
        migrations.AddField(
            model_name='personnes',
            name='Type_personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Type_personne'),
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacth_id', models.FloatField()),
                ('quantite', models.FloatField(max_length=10)),
                ('Livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Livraison')),
                ('Medicaments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Medicaments')),
            ],
        ),
    ]
