# Generated by Django 3.0.8 on 2020-07-29 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='quantite',
            new_name='quantite_batch',
        ),
    ]
