# Generated by Django 3.0.8 on 2020-08-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdc', '0002_auto_20200810_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='Livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='cdc.Livraison'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='cdc.Medicament'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='cdc.Fournisseur', verbose_name='le fournisseur de la livraison'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='type_personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes', to='cdc.Type_personne', verbose_name='la personne qui récupère les médicaments'),
        ),
        migrations.AlterField(
            model_name='recuperation',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperations', to='cdc.Medicament'),
        ),
        migrations.AlterField(
            model_name='recuperation',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperations', to='cdc.Personne'),
        ),
        migrations.AlterField(
            model_name='type_personne',
            name='description',
            field=models.TextField(help_text='description du type de personne'),
        ),
    ]
