# Generated by Django 3.0.8 on 2020-07-31 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cdc', '0002_auto_20200729_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=30, verbose_name='nom du Médicament')),
                ('alerte', models.CharField(max_length=70, verbose_name='seuil à ne pas franchir')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, verbose_name='code personne')),
                ('nom', models.CharField(max_length=40, verbose_name='nom de la personne')),
                ('prenom', models.CharField(max_length=50, verbose_name='prenom de la personne')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
            },
        ),
        migrations.RemoveField(
            model_name='personnes',
            name='Type_personne',
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batch'},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'verbose_name': 'Fournisseur', 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AlterModelOptions(
            name='livraison',
            options={'verbose_name': 'Livraision', 'verbose_name_plural': 'Livraisons'},
        ),
        migrations.AlterModelOptions(
            name='recuperation',
            options={'verbose_name': 'Recuperation', 'verbose_name_plural': 'Recuperations'},
        ),
        migrations.AlterModelOptions(
            name='type_personne',
            options={'verbose_name': 'Type de personne', 'verbose_name_plural': 'Type de personnes'},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Medicaments',
        ),
        migrations.RemoveField(
            model_name='recuperation',
            name='Medicaments',
        ),
        migrations.RemoveField(
            model_name='recuperation',
            name='Personnes',
        ),
        migrations.AlterField(
            model_name='batch',
            name='bacth_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='code',
            field=models.CharField(max_length=25, verbose_name='le code du fournisseur'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom_fournisseur',
            field=models.CharField(max_length=100, verbose_name="le nom de l'organisme fournisseur"),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date',
            field=models.DateField(verbose_name='date de livraison'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Fournisseur', verbose_name='le fournisseur de la livraison'),
        ),
        migrations.AlterField(
            model_name='recuperation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recuperation',
            name='quantite',
            field=models.FloatField(max_length=10, verbose_name='Quantité recuperée'),
        ),
        migrations.AlterField(
            model_name='type_personne',
            name='description',
            field=models.TextField(verbose_name='description du type de personne'),
        ),
        migrations.AlterField(
            model_name='type_personne',
            name='libelle',
            field=models.CharField(max_length=70, verbose_name='la personne qui récupère les médicaments'),
        ),
        migrations.DeleteModel(
            name='Medicaments',
        ),
        migrations.DeleteModel(
            name='Personnes',
        ),
        migrations.AddField(
            model_name='personne',
            name='Type_personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdc.Type_personne', verbose_name='la personne qui récupère les médicaments'),
        ),
        migrations.AddField(
            model_name='batch',
            name='medicament',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='cdc.Medicament'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuperation',
            name='medicaments',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='cdc.Medicament'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuperation',
            name='personne',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='cdc.Personne'),
            preserve_default=False,
        ),
    ]
