# Generated by Django 3.0.8 on 2020-07-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdc', '0003_auto_20200729_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='medicaments',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='personnes',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='recuperation',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='type_personne',
            name='font_size',
        ),
    ]
