# Generated by Django 3.0.8 on 2020-07-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdc', '0003_auto_20200731_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='bacth_id',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
