# Generated by Django 3.0.8 on 2020-07-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdc', '0004_auto_20200729_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='nom',
            new_name='nom_fournisseur',
        ),
        migrations.RenameField(
            model_name='medicaments',
            old_name='nom',
            new_name='nom_medicament',
        ),
    ]
