# Generated by Django 3.0.8 on 2020-07-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdc', '0006_auto_20200729_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='created',
        ),
    ]
